### ISSUE TITLE
[bug] cyan does not fix names like `libsubstrate.dylib`

### ISSUE THREAD

**Issue by TheNightRider12** [asdfzxcvbn/pyzule-rw#6]
### have you searched the existing issues?

- [X] this is a unique issue. i agree that if this isn't a unique issue, i'll be BLOCKED from the cyan repo

### describe the bug.

When building an IPA with the rewrite, I am running into a crashing issue with an app that I build with it. When building Rocket For Instagram with the tweak file, the Cephi framework and the SideloadFix for Instagram being sideloaded, it seems like the Sideload fix .dylib is trying to load libsubstrate.dylib, which is not present. Causing the app to crash on launch. 

However, when I have built this in the past, and even now, to test, using the non-rewrite version of pyzule, using the same .debs and the same SideloadFix dylib, I do not crash, and I do not get the libsubstrate.dylib reason for the crash (no crashes at all when build using the pre-rewrite pyzule). 
![IMG_0626](https://github.com/user-attachments/assets/c944050c-2560-44b1-9ae3-2afed50720e3)

**Comment by asdfzxcvbn** [comment]
yeah, the code for the "better support for manually modified dylibs" feature in pyzule was terrible, so i decided to take it out

you can see how it worked in pyzule: https://github.com/asdfzxcvbn/pyzule/blob/fc5ed8342cf852fd522dbdd68a7aedbea613d194/pyzule.py#L455


vs how it works in cyan: https://github.com/asdfzxcvbn/pyzule-rw/blob/46752d0a26fb5fe057cc66ebfba6afaa90d62225/cyan/tbhtypes/executable.py#L119

overall the code is way cleaner (imo) and less loops are needed. users would have to manually fix the shitty libsubstrate dependency with `install_name_tool` to something like `@rpath/CydiaSubstrate.framework/CydiaSubstrate`

i really wanted to keep this "feature" but due to how substrate has so many names ([which is stupid, btw](https://github.com/asdfzxcvbn/pyzule-rw/blob/46752d0a26fb5fe057cc66ebfba6afaa90d62225/cyan/tbhtypes/executable.py#L24)) it would have to be implemented in some sucky way. i tried but all the "solutions" i came up with were shit and didn't work for me so i decided to leave it out.

if someone is willing to open a PR to implement fixing names like `libsubstrate.dylib` or `CydiaSubstrate.dylib` like in pyzule, i would gladly review it. of course the code needs to remain clean, with little loops, and be readable (unlike pyzule lmao)

**Comment by asdfzxcvbn** [comment]
oh by the way, you don't need to inject sideloadfix when you have rocket. rocket already contains sideload fixes

**Comment by asdfzxcvbn** [comment]
fixed in [v1.4](https://github.com/asdfzxcvbn/pyzule-rw/releases/tag/v1.4)
